name: Run tests

on:
  push:
    branches-ignore:
      - main

env:
  HELM_DOCS_VERSION: '1.5.0'

jobs:
  helm-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # TODO use Docker image if GitHub Actions ever allows mounting the source directory as a volume
    - name: Download helm-docs
      run: |
        curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v${{ env.HELM_DOCS_VERSION }}/helm-docs_${{ env.HELM_DOCS_VERSION }}_Linux_x86_64.tar.gz | \
          tar xzf - helm-docs

    - name: Update docs
      run: |
        for chart in charts/*; do
          pushd $chart && $GITHUB_WORKSPACE/helm-docs -o README.md.new; popd
        done

    - name: Check diff output
      run: |
        git diff-index --name-only --exit-code HEAD

  chart-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1
      with:
        version: v3.4.0

    - name: Run chart-testing (lint)
      run: ct lint --config ct.yaml

      # TODO test install
      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.1.0
      #   if: steps.list-changed.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   run: ct install --config ct.yaml
    
  kubeconform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate and validate releases
      uses: docker://ghcr.io/shivjm/helm-kubeconform-action:v0.1.0
      env:
        ADDITIONAL_SCHEMA_PATHS: |
          schemas/{{ .ResourceKind }}.json
        CHARTS_DIRECTORY: "charts"
        KUBECONFORM_STRICT: "true"
        HELM_UPDATE_DEPENDENCIES: "true"
        
